#!/bin/bash
MAXFREQ=$(echo "$(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_max_freq) - 1000000" | bc)
MINFREQ=$(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_min_freq)

command_exists () {
  type "$1" &> /dev/null ;
}

if command_exists cpufreq-set; then
  for i in {0..3}; do sudo cpufreq-set -c $i -g ondemand; sudo cpufreq-set -c $i --max $MAXFREQ; sudo cpufreq-set -c $i --min $MINFREQ; echo "cpu $i set to performance"; done
  cpufreq-info
fi
if command_exists cpupower; then
  sudo cpupower frequency-set --min $MINFREQ --max $MAXFREQ --governor powersave
  sudo cpupower frequency-info
fi
