#!/bin/bash
# this is a short script that 
# prints out the top heaviest files in a directory
# or the heaviest directories
# Linux Server Hack #15
# http://archive.oreilly.com/pub/h/15
du -cks * |sort -rn |head -21
