#!/bin/bash
#mkdir /mnt/$1
if [ $# -ne 4 ]; then
        # Print usage
        echo 'wrong!!! bad operator!!!
        usage:
        Nu SERVERNAME IPADDRESS|HOSTNAME USERNAME PORT
        e.g.
        Nu Saruman 65.67.51.189 root 2222
        '
            exit 1
fi
echo "
my Name is $1, my port is $4, and my IP address is $2
your username is $3
I will now complete these commands:
mkdir /mnt/$1
and make these scripts
~/bin/$1
~/bin/Mount$1
"

mkdir -p ~/bin
mkdir -p ~/mnt/$1
echo "#!/bin/bash
sshfs -p $4 $3@$2:/ ~/mnt/$1
">~/bin/Mount$1
chmod +x ~/bin/Mount$1
echo "#!/bin/bash
ssh -A -X -p $4 $3@$2 \$@
">~/bin/$1
chmod +x ~/bin/$1
