#!/bin/sh
cd /tmp
git clone git@github.com:octohost/jekyll.git && cd jekyll
git remote add octo git@serve.octodev.io:jekyll.git
time git push octo master
chromium http://jekyll.octodev.io/ &
cd /tmp
git clone git@github.com:octohost/harp.git && cd harp
git remote add octo git@serve.octodev.io:harp.git
time git push octo master
chromium http://harp.octodev.io/ &
cd /tmp
git clone git@github.com:octohost/mojolicious-app.git && cd mojolicious-app
git remote add octo git@serve.octodev.io:mojolicious-app.git
time git push octo master
chromium http://mojolicious-app.octodev.io/ &
cd /tmp
git clone git@github.com:octohost/metalsmith.git && cd metalsmith
git remote add octo git@serve.octodev.io:metalsmith.git
time git push octo master
chromium http://metalsmith.octodev.io/ &
cd /tmp
git clone git@github.com:octohost/wintersmith.git && cd wintersmith
git remote add octo git@serve.octodev.io:wintersmith.git
time git push octo master
chromium http://wintersmith.octodev.io/ &
cd /tmp
git clone git@github.com:octohost/martini.git && cd martini
git remote add octo git@serve.octodev.io:martini.git
time git push octo master
chromium http://martini.octodev.io/ &
