#!/bin/bash
# parmer


# Config
APM=123
SPINDOWN=242


# Main
main() {

  if [ $# -eq 0 ]
    then
      echo "No arguments supplied - printing help"
		  usage
		  exit 1
  fi

  local FIRST_ARG=$1

	if [[ "$FIRST_ARG" == '-h' || "$FIRST_ARG" == '--help'  ]]; then
		usage
		exit 1
	elif [[ "$FIRST_ARG" == '-l' || "$FIRST_ARG" == '--long'  ]]; then
    longshots
		exit 1
  else
    parmit $FIRST_ARG
	fi

}

# Help
usage() {
	echo -e "Parmer - The HD parmer\n"
	echo "Usage:"
	echo -e "parmer\t\t /dev/sdb-     Uses HDparm to
set your hard drive to the parameters in config above"
	echo -e "parmer -h\t- give this help"
}

parmit () {
  sudo hdparm -B 123 $1
  sudo hdparm -S 242  $1
}


main "$@"
