#!/bin/bash
# parmer

# Config
APM=123
SPINDOWN=242
# Homedir overrides
source ~/.parmer.cfg


if [ -n "${1+1}" ]; then
  echo "1 is defined"
  DRIVE=$1
fi

# Main
main() {

	if [[ "$DRIVE" == '-h' || "$DRIVE" == '--help'  ]]; then
		usage
		exit 1
  else
    parmit $DRIVE
	fi

}

# Help
usage() {
	echo -e "Parmer - The HD parmer\n"
	echo "Usage:"
	echo -e "parmer\t\t /dev/sdb-     Uses HDparm to
set your hard drive to the parameters in config above"
	echo -e "parmer -h\t- give this help"
	echo -e "config file --> ~/.parmer.cfg"
	echo -e "\texport APM=123
\texport SPINDOWN=242
\texport DRIVE=/dev/sdb"

}

parmit () {
  sudo hdparm -B 123 $1
  sudo hdparm -S 242  $1
}


main "$@"
