#!/bin/bash
# some collected methods from this page:
# http://www.howtogeek.com/howto/30184/10-ways-to-generate-a-random-password-from-the-command-line/

# turn into a function like this, and place in .bashrc
# randpw(){ < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-16};echo;}

date +%s | sha256sum | base64 | head -c 32 ; echo

< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;

openssl rand -base64 32

tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1

strings /dev/urandom | grep -o '[[:alnum:]]' | head -n 30 | tr -d '\n'; echo

< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c6

dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 0 | rev | cut -b 2- | rev

</dev/urandom tr -dc '12345!@#$%qwertQWERTasdfgASDFGzxcvbZXCVB' | head -c8; echo ""

date | md5sum
