#!/bin/bash
# change all cpu cores to performance governor
# this may not be optimal on the newest intel cpus
# https://wiki.archlinux.org/index.php/CPU_frequency_scaling#i7z
for i in {0..7}; do cpufreq-set -c $i -g performance; cpufreq-set -c $i --max 3.4GHz; cpufreq-set -c $i --min 800MHz; echo "cpu $i set to performance"; done
cpufreq-info
