#!/bin/bash
FREQ="1.7GHz"

for i in {0..3}; do sudo cpufreq-set -c $i -g powersave; sudo cpufreq-set -c $i --max $FREQ; sudo cpufreq-set -c $i --min $FREQ; echo "cpu $i set to powersave"; done
#cpufreq-info
